apiVersion: apps/v1
kind: Deployment
metadata:
  name: catping
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: catping
  template:
    metadata:
      labels:
        app: catping
    spec:
      containers:
      - image: docker.io/viveknidhi22/catping
        name: catping
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred 
---
apiVersion: v1
kind: Service
metadata:
  name: catping-svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: catping      